# Generated by Django 2.1.1 on 2018-09-05 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0004_auto_20180904_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 15, 46, 30, 72528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 5, 46, 30, 72445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 15, 46, 30, 71260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 5, 46, 30, 71182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 15, 46, 30, 69661, tzinfo=utc)),
        ),
    ]
