# Generated by Django 2.1.1 on 2018-09-08 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0006_auto_20180905_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 14, 31, 6, 17978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 4, 31, 6, 17958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 14, 31, 6, 17580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 4, 31, 6, 17557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 14, 31, 6, 7747, tzinfo=utc)),
        ),
    ]
