# Generated by Django 2.1.1 on 2018-09-13 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0009_auto_20180910_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='break_needed_afterwards',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='task',
            name='max_repeats_per_day',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='task',
            name='times_repeated_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='hard_bound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='minimum_time_to_devote',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 19, 46, 14, 738439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 10, 46, 14, 738415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 19, 46, 14, 738033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 10, 46, 14, 738005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 19, 46, 14, 723793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(19, 46, 14, 738755)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 46, 14, 738732)),
        ),
    ]
