# Generated by Django 2.1.1 on 2018-09-13 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0009_auto_20180910_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='break_needed_afterwards',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='task',
            name='max_repreats_per_day',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='hard_bound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='minimum_time_to_devote',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 18, 19, 24, 160297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 9, 19, 24, 160219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 18, 19, 24, 159149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 9, 19, 24, 159075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 18, 19, 23, 976999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 19, 24, 161102)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 19, 24, 161053)),
        ),
    ]
