# Generated by Django 2.1.1 on 2018-09-17 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0010_auto_20180913_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='done',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 19, 28, 52, 766053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 10, 28, 52, 766030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 19, 28, 52, 765632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 10, 28, 52, 765604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 19, 28, 52, 755927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(19, 28, 52, 766369)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 28, 52, 766345)),
        ),
    ]
