# Generated by Django 2.1.1 on 2018-09-21 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0011_auto_20180917_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 20, 32, 0, 776632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 11, 32, 0, 776600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 20, 32, 0, 776196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 11, 32, 0, 776169, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 20, 32, 0, 766050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 32, 0, 776949)),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(11, 32, 0, 776927)),
        ),
    ]
